{ socket: 
   { _handle: 
      { writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 639,
     _bytesDispatched: 0,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     _paused: false,
     server: 
      { _connections: 2,
        connections: [Getter/Setter],
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false,
        _connectionKey: '4:0.0.0.0:8000' },
     _events: 
      { drain: [Function: ondrain],
        timeout: [Object],
        error: [Function],
        close: [Object] },
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        _paused: false,
        server: [Object],
        _events: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Fri Jun 21 2013 18:09:32 GMT-0400 (EDT),
        parser: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Fri Jun 21 2013 18:09:32 GMT-0400 (EDT),
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  connection: 
   { _handle: 
      { writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 639,
     _bytesDispatched: 0,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     _paused: false,
     server: 
      { _connections: 2,
        connections: [Getter/Setter],
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false,
        _connectionKey: '4:0.0.0.0:8000' },
     _events: 
      { drain: [Function: ondrain],
        timeout: [Object],
        error: [Function],
        close: [Object] },
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        _paused: false,
        server: [Object],
        _events: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Fri Jun 21 2013 18:09:32 GMT-0400 (EDT),
        parser: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Fri Jun 21 2013 18:09:32 GMT-0400 (EDT),
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  httpVersion: '1.1',
  complete: false,
  headers: 
   { host: 'localhost:8000',
     connection: 'keep-alive',
     'cache-control': 'max-age=0',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.110 Safari/537.36',
     'accept-encoding': 'gzip,deflate,sdch',
     'accept-language': 'en-US,en;q=0.8',
     cookie: 'request_method=GET; _qpcpartners_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFRkkiJWNlYWQ0NzdjMDI2YWVjYjEwMzU1ZjdiN2E4YWU2NTIwBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMW5aYzdVcjBESUlNTC9IUy9ueUYxZ0l6cXBVUHZJeEJyU0RTeHV1YUNVMEU9BjsARg%3D%3D--f3d5e307c6cd9eade862f6031e48b3c9e1e01897' },
  trailers: {},
  readable: true,
  _paused: false,
  _pendings: [],
  _endEmitted: false,
  url: '/',
  method: 'GET',
  statusCode: null,
  client: 
   { _handle: 
      { writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 639,
     _bytesDispatched: 0,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     _paused: false,
     server: 
      { _connections: 2,
        connections: [Getter/Setter],
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false,
        _connectionKey: '4:0.0.0.0:8000' },
     _events: 
      { drain: [Function: ondrain],
        timeout: [Object],
        error: [Function],
        close: [Object] },
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        _paused: false,
        server: [Object],
        _events: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Fri Jun 21 2013 18:09:32 GMT-0400 (EDT),
        parser: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Fri Jun 21 2013 18:09:32 GMT-0400 (EDT),
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  upgrade: false }